all:04

04: 06_04.o Car.o MCycle.o Truck.o Vehicle.o
	g++ -o 04 06_04.o Car.o MCycle.o Truck.o Vehicle.o
    
06_04.o: 06_04.cpp
	g++ -c 06_04.cpp
    
Car.o: Car.cpp
	g++ -c Car.cpp
    
MCycle.o: MCycle.cpp
	g++ -c MCycle.cpp
	
Truck.o: Truck.cpp
    g++ -c Truck.cpp
    
Vehicle.o: Vehicle.cpp
	g++ -c Vehicle.cpp
