all:01

01: 04_01.o Q_Add.o MyRandom.o
	g++ -o 01 04_01.o Q_Add.o MyRandom.o
	
04_01.o: 04_01.cpp
	g++ -c 04_01.cpp

Q_Add.o: Q_Add.cpp
	g++ -c Q_Add.cpp
	
MyRandom.o: MyRandom.cpp
	g++ -c MyRandom.cpp
