all:03

03: 07_03.o Detective.o Comic.o Novel.o Book.o 
	g++ -o 03 07_03.o Detective.o Comic.o Novel.o Book.o
	
07_03.o: 07_03.cpp
	g++ -c 07_03.cpp
	
Detective.o: Detective.cpp
	g++ -c Detective.cpp

Comic.o: Comic.cpp
	g++ -c Comic.cpp

Novel.o: Novel.cpp
	g++ -c Novel.cpp
			
Book.o: Book.cpp
	g++ -c Book.cpp

